# Form implementation generated from reading ui file '5_test_designer.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TestQt(object):
    def setupUi(self, TestQt):
        TestQt.setObjectName("TestQt")
        TestQt.resize(640, 452)
        TestQt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(TestQt)
        self.centralwidget.setObjectName("centralwidget")
        TestQt.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TestQt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 24))
        self.menubar.setObjectName("menubar")
        self.menuTest_Qt_designer = QtWidgets.QMenu(self.menubar)
        self.menuTest_Qt_designer.setObjectName("menuTest_Qt_designer")
        TestQt.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TestQt)
        self.statusbar.setObjectName("statusbar")
        TestQt.setStatusBar(self.statusbar)
        self.actionFile = QtGui.QAction(TestQt)
        self.actionFile.setObjectName("actionFile")
        self.actionFile_2 = QtGui.QAction(TestQt)
        self.actionFile_2.setObjectName("actionFile_2")
        self.action = QtGui.QAction(TestQt)
        self.action.setObjectName("action")
        self.menuTest_Qt_designer.addAction(self.actionFile)
        self.menuTest_Qt_designer.addAction(self.actionFile_2)
        self.menuTest_Qt_designer.addAction(self.action)
        self.menubar.addAction(self.menuTest_Qt_designer.menuAction())

        self.retranslateUi(TestQt)
        QtCore.QMetaObject.connectSlotsByName(TestQt)

    def retranslateUi(self, TestQt):
        _translate = QtCore.QCoreApplication.translate
        TestQt.setWindowTitle(_translate("TestQt", "Test Qt designer"))
        self.menuTest_Qt_designer.setTitle(_translate("TestQt", "Test Qt designer"))
        self.actionFile.setText(_translate("TestQt", "File"))
        self.actionFile_2.setText(_translate("TestQt", "File 2"))
        self.action.setText(_translate("TestQt", "File 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TestQt = QtWidgets.QMainWindow()
    ui = Ui_TestQt()
    ui.setupUi(TestQt)
    TestQt.show()
    sys.exit(app.exec())
